[versions]
allegro-opel = "1.1.14"
apache-commons-lang3 = "3.16.0"
spotify-completable-futures = "0.3.6"
adventure = "4.17.0"
parboiled = "1.4.1"

[libraries]
opel = { module = "pl.allegro.tech:opel", version.ref = "allegro-opel" }
lang = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
futures = { module = "com.spotify:completable-futures", version.ref = "spotify-completable-futures" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
parboiled = { module = "org.parboiled:parboiled-java", version.ref = "parboiled" }

[bundles]
adventure = ["adventure-api", "adventure-minimessage"]